// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgG8T53UU2L0yjWNeLhEbe3Xa_PmDl8c',
    appId: '1:386874559203:web:a98712024b61fc67a053d6',
    messagingSenderId: '386874559203',
    projectId: 'guard-x-8f966',
    authDomain: 'guard-x-8f966.firebaseapp.com',
    storageBucket: 'guard-x-8f966.firebasestorage.app',
    measurementId: 'G-ST6K8L1WZZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nsXp8KUerHnEX1w2nUdSnmzomrNA47o',
    appId: '1:386874559203:ios:e802f5f741603793a053d6',
    messagingSenderId: '386874559203',
    projectId: 'guard-x-8f966',
    storageBucket: 'guard-x-8f966.firebasestorage.app',
    iosBundleId: 'com.example.guardx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_nsXp8KUerHnEX1w2nUdSnmzomrNA47o',
    appId: '1:386874559203:ios:e802f5f741603793a053d6',
    messagingSenderId: '386874559203',
    projectId: 'guard-x-8f966',
    storageBucket: 'guard-x-8f966.firebasestorage.app',
    iosBundleId: 'com.example.guardx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdgG8T53UU2L0yjWNeLhEbe3Xa_PmDl8c',
    appId: '1:386874559203:web:0b941923268aa96ca053d6',
    messagingSenderId: '386874559203',
    projectId: 'guard-x-8f966',
    authDomain: 'guard-x-8f966.firebaseapp.com',
    storageBucket: 'guard-x-8f966.firebasestorage.app',
    measurementId: 'G-326E78NS8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApRvyGW5h-9lso_YFkHbqfblxpVR9Rss8',
    appId: '1:386874559203:android:c007e38643cd118fa053d6',
    messagingSenderId: '386874559203',
    projectId: 'guard-x-8f966',
    storageBucket: 'guard-x-8f966.firebasestorage.app',
  );

}